# Generated by Django 3.1.7 on 2021-03-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210328_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieshots',
            old_name='iamge',
            new_name='image',
        ),
    ]
